# https://github.com/yaoyao-liu/minimal-light
# https://github.com/yaoyao-liu/yaoyao-liu.github.io

# Basic Information 
title: Shunto J. Kobayashi
position: Assistant Professor of Marketing
affiliation: Boston University Questrom
email: sjkobaya@bu.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: shunto kobayasi, shunto jerry kobayashi, sjkobayashi, skobayashi, caltech, empirical industrial organization, econometrics, applied microeconomics, bu questrom, marketing, quant marketing
description: Assistant Professor of Marketing at BU Questrom. Research interests include Empirical Industrial Organization and Econometrics.
canonical: https://shuntokobayashi.com

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=_tWe3CIAAAAJ
# github_link: https://github.com/sjkobayashi
# linkedin: https://www.linkedin.com/in/shunto-kobayashi/
cv_link: assets/files/shunto-kobayashi-cv.pdf
# twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.jpg
favicon_dark: ./assets/img/favicon.jpg

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Sans Serif" # or "Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
